var alexBankResources = {
    Language: "Ar",
    SecLanguage: "En",
    CheckBalance: "Check Points Balance",
    Homepage: "Home",
    ALEXPOINTS: "ALEXPOINTS",
    ALEXDISCOUNTS: "ALEXDISCOUNTS",
    AboutProgram: "Everything about <br>ALEXREWARDS",
    Terms_Conditions: "Terms & Conditions",
    Contact_Us: " Contact Us",
    Download_the_App: "Download the App",
    Follow_Us: "Follow Us",
    All_rights_reserved: "&copy; 2018 AlexBank. All rights reserved",
    Check_your_balance: "Check your balance",
    enter_the_pin: "Please enter the verification pin code in the field below. <br/>In case you didn’t receive the SMS click resend code.",
    Enter_verification_code: "2. Enter the verification code",
    Next: "Next",
    not_receive_SMS: "didn’t receive the SMS? ",
    Resend_code: "Resend code",
    ALEXPOINTS_balance_details: "ALEXPOINTS balance details",
    Thank_You: " Thank You",
    Mobile_Number: "Mobile Number",
    points: "points",
    EGP: "EGP",
    Redemption: "Redemption",
    Collection: "Collection",
    Date_Time: "Date/Time",
    Partner: "Partner",
    Branch: "Branch",
    Points: "Points",
    Value: "Value",
    Check_balance_mobile_body: "You can check your balance of ALEXPOINTS by entering your mobile number<br/>in the field below and you will receive an SMS with a verification pin code",
    enter_mobile: "1. Please enter your mobile number",
    not_eligible_body: "Dear customer, you are not eligible to use this service",
    aboutPage_1: "Learn more about the ALEXREWARDS",
    aboutPage_2: "ALEXREWARDS is a Loyalty Program provided by ALEXBANK to its customers and offering<br/>them special discounts through ALEXDISCOUNTS and the opportunity to collect and redeem points through ALEXPOINTS.",
    aboutPage_3: "How to register for ALEXREWARDS Benefits:",
    aboutPage_4: "You will be enrolled automatically and free without filling in applications.",
    aboutPage_5: "ALEXPOINTS Program Details:",
    aboutPage_6: "Only with ALEXPOINTS program, you will collect points on your diverse banking products transactions that include:",
    aboutPage_7: "All Local & International Credit Card Transactions.",
    aboutPage_8: "All Local & International Debit Card Transactions.",
    aboutPage_9: 'Internet banking account activation and external transfers "to other banks" through the Internet banking service.',
    aboutPage_10: "Average Monthly Ending Balances of AlexPlus current accounts and savings accounts average monthly ending balances (only for MAGNIFICA and Private customers)",
    aboutPage_11: "Free welcome points when you join as a new MAGNIFICA customer, new Private customer, upgrades to be MAGNIFICA & Private customer.",
    aboutPage_12: "How to Collect Points:",
    Credit_Cards_details: " Point of Sale Local & International<br/>Transactions and Online Transactions",
    VISA_Classic_Card_details: "1 Point for every 1 EGP Spent",
    VISA_Gold_Card_details: "1.25 Points for every 1 EGP Spent",
    MasterCard_Platinum_Card_details: "1.75 Points for every 1 EGP Spent",
    Debit_Cards_details: "Point of Sale Local & International<br/>Transactions and Online Transactions",
    VISA_Masry_Card_details: "1 Point for every 1 EGP Spent",
    aboutPage_13: "Average Monthly Ending<br/>Balance in AlexPlus Account",
    aboutPage_14: "How to know my points collected and the merchants participating in the program:",
    aboutPage_15: "Call ALEXBANK contact Center on 19033.",
    aboutPage_16: "ALEXREWARDS Website through alexbank.com",
    aboutPage_17: "Download ALEXREWARDS mobile application",
    Banking_Product: "Banking Product",
    Type: "Type",
    Points_Collected: "Points Collected",
    Credit_Cards: "Credit Cards",
    VISA_Classic_Card: "VISA Classic Card",
    VISA_Gold_Card: "VISA Gold Card",
    MasterCard_Platinum_Card: "MasterCard Platinum Card",
    Debit_Cards: "Debit Cards",
    VISA_Masry_Card: "VISA Masry Card",
    VISA_Youth_Card: "VISA Youth Card",
    VISA_Youth_Card_details: "1 Point for every 1 EGP Spent",
    VISA_Inspire_Card: "VISA Inspire Card",
    VISA_Inspire_Card_details: "1.25 Point for every 1 EGP Spent",
    VISA_Platinum_Card: "VISA Platinum Card",
    VISA_Platinum_Card_details: "1.5 Point for every 1 EGP Spent",
    Free_Welcome_Points: "Free Welcome Points",
    New_Upgraded_MAGNIFICA_Customer: "New or Upgraded MAGNIFICA Customer",
    New_Upgraded_MAGNIFICA_Customer_details: "50,000 Points",
    New_Upgraded_Private_Customer: "New or Upgraded Private Customer",
    New_Upgraded_Private_Customer_details: "500,000 Points",
    Internet_Banking: "Internet Banking",
    Activating_Service: "Activating Service",
    Activating_Service_details: "500 Points",
    External_Transfers_1: "From 1 – 15 External Transfers",
    External_Transfers_1_details: "320 Points per transfer",
    External_Transfers_2: "From 16 - 30 External Transfers",
    External_Transfers_2_details: "400 Points per transfer",
    External_Transfers_3: "From 31- 45 External Transfers",
    External_Transfers_3_details: "480 Points per transfer",
    Only_Private_MAGNFICA_Customers: "Only For Private & MAGNFICA Customers",
    MAGNIFICA_Customer: "MAGNIFICA Customer",
    MAGNIFICA_Customer_details: "50 Points for every 1,000 EGP",
    Private_Customer: "Private Customer",
    Private_Customer_details: "100 Points for every 1,000 EGP",
    How_redeem_Points: "How to redeem Points collected:",
    How_redeem_Points_details: "Visit any of the merchants participating in ALEXPOINTS, inform the cashier<br/>with your mobile number registered in the Bank and you will be able to redeem any amount of your points.",
    Important_notes: "Important notes:",
    Important_notes1: "Points expire after 2 years from collected.",
    Important_notes2: "Make sure to update your data to ensure you are able to register on ALEXREWARDS Program",
    Important_notes3: "Points cannot be transferred to another customer",
    ALEXDISCOUNTS_Program_Details: "ALEXDISCOUNTS Program Details:",
    ALEXDISCOUNTS_Program_Details1: "Special discounts when paying with any of your ALEXBANK Credit or Devit cards at our merchants participating in ALEXDISCOUNTS Program.",
    ALEXDISCOUNTS_Program_Details2: "How to know the discounts details and the merchants participating in the program:",
    All_Partners: "All Partners",
    Branches: "Branches",
    How_to_redeem: "How to redeem",
    AlexRewards: "ALEXREWARDS",
    HomePageParagraph: "For being a part of Alex bank, the gifts will just keep on coming, with the new ALEXREWARDS program from Alex Bank which will give you the appreciation you deserve through many rewards and benefits. the more points you collect in your unified account, which can then be redeemed as discounts from our partners.<br>To learn more, call 0123 or 0123456789 from mobile or landline or stop by our branches.",
    Deal_of_the_month: "Deal of the month",
    Details: "Details",
    ContactUsParagraph: "For more information about ALEXREWARDS program 24/7",
    ALEXREWARDS_Program_Terms_Conditions: "ALEXREWARDS Program Terms and Conditions",
    General_rules: "General rules:",
    TermsConditionPage_1: "ALEXBANK REWARDS is a reward program consisting of ALEXPOINTS and ALEXDISCOUNTS.",
    TermsConditionPage_2: "You agree to subscribe to the Program in accordance with these terms, which<br/>you must read in addition to reading the terms and conditions of opening the bank account,<br/>issuing the credit card, issuing the debit card and the bank's Internet banking.",
    TermsConditionPage_3: "You will be automatically enrolled in the program free of charge without having to apply.",
    TermsConditionPage_4: "We may cancel your enrollment in ALEXREWARDS program in case of any of the following:",
    Cards: "Cards:",
    TermsConditionPage_5: "Closing your account, your card or any of your banking products belonging to ALEXBANK.",
    TermsConditionPage_6: "You are under law or legal liability.",
    TermsConditionPage_7: "Delay payment of any of your accounts for any reason.",
    TermsConditionPage_8: "Violation of any of the terms of our banking contract.",
    TermsConditionPage_9: "At any time and without any prior notice or liability to the Client, ALEXBANK reserves the right to cancel ALEXREWARDS program<br/>and/or cancel and/or modify its features an/or change, add or delete the Rewards Program Subscribers and/or modify or reduce<br/>the value of the points and/or the way the points are exchanged, even if these measures will reduce the value of the reward<br/>points already earned, with the knowledge of the Bank and without any prior notice.",
    TermsConditionPage_10: "ALEXPOINTS Points Program Terms and Conditions:",
    TermsConditionPage_11: "ALEXPOINTS is a reward system that gives you points when you use any of the following products:",
    TermsConditionPage_12: "Cardholders: All purchases of credit cards and debit cards (excluding corporate cards).",
    TermsConditionPage_13: "Free welcome points when you join as a new MAGNIFICA customer or new Private customer.",
    TermsConditionPage_14: "Accounts - AlexPlus current accounts and savings accounts average monthly ending balances (only for MAGNIFICA and Private customers)",
    TermsConditionPage_15: 'Internet banking account activation and external transfers "to other banks" through the Internet banking service.',
    TermsConditionPage_16: "You will earn points for each 1 EGP Spend daily in purchases,<br/>according to the value of the current transaction with your<br/>credit card and debit card and rounded to the nearest point.",
    TermsConditionPage_17: "The following operations are not included in the calculation of earning points:",
    TermsConditionPage_18: "Cash payments or cash withdrawals from ATMs.",
    TermsConditionPage_19: "Annual administration expenses for cards.",
    TermsConditionPage_20: "Interest or commissions charged when credit card payments are delayed.",
    TermsConditionPage_21: "Late payment charges.",
    TermsConditionPage_22: "Expenses and commissions recovered from the credit card account.",
    TermsConditionPage_23: "To participate in the program, your credit card accounts must be<br/>in good financial condition. All program privileges is granted<br/>to the primary or supplementary cards earned points are collected on the primary card.",
    TermsConditionPage_24: "If you are the primary cardholder, you can redeem your points in ALEXPOINTS Merchants. The additional cardholder will not be allowed to redeem points.",
    TermsConditionPage_25: "Points cannot be transferred to another account or cardholder.",
    TermsConditionPage_26: "The Cardholder will not collect points relating to any transactions that have<br/>been paid by the Cardholder prior to the date of the launch of ALEXPOINTS program.",
    TermsConditionPage_27: "Points are earned in the following manner:",
    TermsConditionPage_28: "All Credit Card Holders:",
    TermsConditionPage_29: "Points of sale purchases and online payments:",
    TermsConditionPage_30: "Visa Classic Credit Cards - 1 point for each 1 EGP spend",
    TermsConditionPage_31: "Visa Gold Credit Cards - 1.25 points for each 1 EGP spend",
    TermsConditionPage_32: "MasterCard Platinum Credit Cards - 1.75 points for each 1 EGP spent",
    TermsConditionPage_33: "1.	Points of sale purchases and online payments:",
    TermsConditionPage_34: "Local Egyptian Debit Visa Card - 1 point for each 1 EGP spend.",
    TermsConditionPage_35: "Youth Debit Visa Card - 1 point for each 1 EGP spend.",
    TermsConditionPage_36: "INSPIRE International Debit Card - 1.25 points for each 1 EGP spend.",
    TermsConditionPage_37: "Platinum Visa Card - 1.5 points for each 1 EGP spend.",
    TermsConditionPage_38: "MasterCard Liverpool Card - 2 points for each 1 EGP spend.",
    TermsConditionPage_39: "MasterCard Liverpool Youth Card - 1.25 points for each 1 EGP spend.",
    TermsConditionPage_40: "MasterCard Liverpool Special Edition - 3 points for each 1 EGP spend.",
    TermsConditionPage_41: "All MAGNIFICA and PRIVATE customers",
    TermsConditionPage_42: "Previous MAGNIFICA and PRIVATE clients will not collect points relating <br/>to any transactions by their card and account balances prior to the launch date of ALEXPOINTS Program.",
    TermsConditionPage_43: "All Credit Card Holders:",
    TermsConditionPage_44: "New or upgraded to MAGNIFICA customers - 50,000 points",
    TermsConditionPage_45: "New or upgraded to Private customers - 500,000 points",
    TermsConditionPage_46: "MAGNIFICA customers - 50 points for every 1,000 EGP on average monthly balance in the account..",
    TermsConditionPage_47: "Private customers - 100 points for evert 1,000 EGP on average monthly balance in the account.",
    TermsConditionPage_48: "MAGNIFICA customers - 20 points for every 1,000 EGP on average monthly balance in the account..",
    TermsConditionPage_49: "Private customers - 50 points for every 1,000 EGP on average monthly balance in the account..",
    TermsConditionPage_50: "Activation of the service - 500 points",
    TermsConditionPage_51: "Earn points on external transfer transactions to other banks with the following matrix:",
    TermsConditionPage_52: "From 1 – 15 External Transfers: Earn 320 points for each transaction.",
    TermsConditionPage_53: "From 16 – 30 External Transfers: Earn 400 points for each transaction.",
    TermsConditionPage_54: "From 16 – 30 External Transfers: Earn 400 points for each transaction.",
    TermsConditionPage_55: "If you cancel any of your bank products that earn points on, you will<br/>lose points earned from the canceled product. At the same time, you will<br/>continue to earn points normally on other products if you continue to be eligible for the program.",
    TermsConditionPage_56: "When the card is deactivated/cancelled as a result of a breach of the Card Agreement with <br/> the Bank, all points accrued to this Card Account will be canceled.",
    TermsConditionPage_57: "Points redeemed as follows:",
    TermsConditionPage_58: "Points collected at participating stores in the ALEXPOINTS score program are exchanged by mentioning the mobile number registered with the bank.",
    TermsConditionPage_59: "Partners participating in the ALEXPOINTS points program are posted on ALEXBANK website and ALEXREWARDS Mobile Application.",
    TermsConditionPage_60: "Rewards may not be exchanged for other rewards, refund, change or transfer of money or credit under any circumstances.",
    TermsConditionPage_61: "When you need to pay partially to the merchant using points, you can use your credit / debit card to pay the difference or pay in cash.",
    TermsConditionPage_62: "There is no minimum number of points to redeem at stores participating in the ALEXPOINTS score program.",
    TermsConditionPage_63: "All earned points expire 24 months after the date of earning points.",
    TermsConditionPage_64: "The Bank is not responsible for any products or services provided by merchants participating in ALEXREWARDS,<br/>or for the quality or performance of those products and services provided by the partner,<br/> Service Providers or any agency participating in the Program. Any complaint or suspension of<br/>products and services must be addressed to the responsible partner or service provider.",
    TermsConditionPage_65: "ALEXDISCOUNTS Program Terms and Conditions:",
    TermsConditionPage_66: "Not all offers are made by ALEXBANK and therefore we are not responsible for <br/>  the terms and conditions binding for such merchant offer. We therefore <br/> recommend that you read all terms and conditions before using the offer<br/> at merchants participating in the ALEXDISCOUNTS program.",
    TermsConditionPage_67: "Payment must be made by any of ALEXBANK credit or debit cards.",
    TermsConditionPage_68: "Offers do not apply during periods of promotional campaigns, holidays or public holidays unless stated otherwise.",
    TermsConditionPage_69: "The Bank may change the offer without prior notice",
    TermsConditionPage_70: "Any changes related to the offer list will be posted on ALEXBANK website.",
    TermsConditionPage_71: "ALEXBANK may terminate any offer at its sole discretion",
    TermsConditionPage_72: "All Debit Card Holders:",
    Internet_banking_service: "Internet banking service",
    Savings_accounts: "Savings accounts",
    AlexPlus_Accounts: "AlexPlus Accounts",
    Welcome_points: "Welcome points",
    Enter_your_mobile_number_here: "Enter your mobile number here",
    Enter_the_verification_code: "Enter the verification code",
    RequiredCode: "Please enter the verification code",
    PatternCode: "Wrong verification code",
    RequiredMobile: "Please enter a mobile number",
    PatternMobile: "Please enter a valid mobile number",
    NotAMember: "Dear customer, you are not eligible to use this service",
    AlexBankLogo:'<img width="200" src="Content/img/Alex Bank English logo.png" />'
};